Improve scigateway mobile support
ral-facilities/scigateway pull request #1281
Opened 2023-06-15 15:44 UTC by kennethnym

## Description

This PR improves scigatway mobile support by tweaking the overall UI layout on mobile. The following components are modified:

- Top app bar
- Drawer
- Home page
- Footer

### Top app bar

The app bar contains several elements:

- Drawer button
- Website logo
- Page links (e.g. admin page, help page)
- Action buttons (tutorial, settings, etc.)
- User avatar
- Notifications

This is fine on larger viewports, but on smaller viewports there is not enough space to show everything at once. This PR introduces a new mobile overflow menu that consolidates page links, action buttons, and the settings menu into a single menu, accessible through a new menu overflow button that is only visible on small viewports. The app bar retains the current layout on larger viewports.

New mobile overflow menu:

![localhost_3000_(iPhone SE) (1)](https://github.com/ral-facilities/scigateway/assets/19359984/63c7a617-2b43-44b0-9eaa-b62e6976ec3e)

### Drawer

Currently, on larger viewports, the drawer appears next to the main content. On smaller viewports, however, this causes the main content to be too narrow to be readable or usable. This PR tweaks the behavior of the drawer so that it overlaps the main content instead. The drawer is dismissable by clicking outside of the drawer.

The drawer is also changed so that it is hidden by default on small viewports.

New drawer:

![localhost_3000_(iPhone SE)](https://github.com/ral-facilities/scigateway/assets/19359984/369ec465-9d03-4d53-ac75-e5acd90ee487)

### Home page

This PR improves the layout on the home page so that texts are not overflowing and are comfortably readable.

![localhost_3000_(iPhone SE) (2)](https://github.com/ral-facilities/scigateway/assets/19359984/1da44567-6120-4129-81de-6b4526fc18c8)

### Footer

Footer is now hidden on mobile. I don't know if it is required to show the footer on mobile. If it is, a mobile version of the footer needs to be designed.

## Testing instructions
Add a set up instructions describing how the reviewer should test the code

- [ ] Review code
- [ ] Check Actions build
- [ ] Review changes to test coverage

## Agile board tracking
Closes #1280

2023-07-07 10:44 UTC, louise-davies requested changes
Looking good, just a minor issue:

The facility card is squished on mobile:
![image](https://github.com/ral-facilities/scigateway/assets/22525471/f229724f-840b-432d-9ba5-0c8c757e00c1)

But otherwise, I believe it addresses all the issues raised in #1254

2023-07-07 10:46 UTC, louise-davies approved these changes
Actually ignore me - that's me being dumb. The card is only that small because the text content is small - once you fill it with more words in the description it sizes properly 😅

2023-07-07 14:04 UTC, kennethnym commented
I actually think it should take up the whole width regardless of the content, as it looks more natural imo.

2023-07-20 08:28 UTC, louise-davies approved these changes

2023-07-28 13:04 UTC, merged