allow plugins to register helpSteps #442
ral-facilities/scigateway pull request #443
Opened 2020-10-02 14:05 UTC by patrick-austin

## Description
Add optional `helpSteps` to the plugin payload and register the contents for the tour. Retain the previous `helpText` (which only applies to the plugin in the navbar itself) to maintain compatibility if the plugins haven't been updated.

## Testing instructions
Add a set up instructions describing how the reviewer should test the code

- [ ] Review code
- [ ] Check Travis build
- [ ] Review changes to test coverage
- [ ] Check that the `helpText` still displays for plugins using that method of registering tour steps

Testing the new `helpSteps` will require code from ral-facilities/datagateway#430 (not made PR yet)

## Agile board tracking
connect to #442 ral-facilities/datagateway#430

2020-12-01 09:12 UTC, louise-davies requested changes

2020-12-01 09:12 UTC, louise-davies commented on src/state/actions/scigateway.actions.test.tsx
> +    console.log(localStorage.getItem('darkMode'));
remove logging statements

2020-12-01 09:12 UTC, louise-davies commented on src/state/actions/scigateway.actions.test.tsx
> +    console.log(actions);
same here

2020-12-01 09:12 UTC, louise-davies commented on src/state/actions/scigateway.actions.tsx
> +      console.log(preference);
remove

2020-12-01 11:21 UTC, patrick-austin commented
@louise-davies I'll get rid of the logging, with the failing darkmode test should I skip it or leave it in? Assuming it's still failing in the Travis runs.

2020-12-01 11:23 UTC, louise-davies commented
@patrick-austin I'd say just skip it, add in a TODO to investigate and perhaps we should create an issue on the repo? Just to track it.

2020-12-15 09:56 UTC, louise-davies approved these changes

2020-12-15 10:07 UTC, merged