Add footer to display external links at bottom of pages
ral-facilities/scigateway pull request #492
Opened 2020-11-25 16:07 UTC by VKTB

## Description
Adds a footer component that displays external links that direct the user to the facility home, cookie policy and about us pages. To allow facilities to configure these external links and their names, a raw HTML is stored in in the `default.json` file. I noticed that the link names change colour after they have been clicked (which is normal behaviour), so I just wanted to get people's view on whether we want to override this? It seems that is overridden in TopCAT and `text-decoration` is set to `none` to remove the lines under the link names. Given that there are some hyperlinks in the _Cookies_ page, it might better to globalise this if we want the same behaviour there.

The footer component is not tested as I wanted to check whether what I have done so far meets the requirements before writing any tests.

## Testing instructions
- [ ] Review code
- [ ] Check Travis build
- [ ] Review changes to test coverage
- [ ] Change the `html` value of `footer` inside `default.json` to 
```
<a href=\"http://www.diamond.ac.uk\">Diamond Light Source</a> | <a href=\"http://www.diamond.ac.uk/Legal.html\">Privacy Policy</a> | <a href=\"http://www.diamond.ac.uk/Home/About.html\">About Us</a>
``` 
or a raw HTML value of your own choice.
- [ ] Check that the external links are displayed at the bottom of the pages.
- [ ] Check that you are successfully redirected to the external web page when you click on an external link.
## Agile board tracking
connect to #479

2020-12-01 08:52 UTC, louise-davies requested changes
Works well with the plugins, but I think there is too much whitespace around the footer and it takes up too much screen space because of it. Also the font size could also be smaller - again to free up some screen space. Additionally, we'd probably want to reduce the size of the plugins to not need to scroll to the footer, but that is a separate issue.

2020-12-09 11:04 UTC, VKTB commented
@louise-davies Reduced the whitespace and the font size as requested, see screenshots below.

![image](https://user-images.githubusercontent.com/45173816/101621781-20d95800-3a0e-11eb-8fb2-707640b9da0f.png)
---
![image](https://user-images.githubusercontent.com/45173816/101621811-26cf3900-3a0e-11eb-92a4-635ce0f84394.png)

2021-01-07 09:18 UTC, louise-davies approved these changes
Looks good - there'll probably need to be a separate issue opened in DataGateway to adjust the plugin container sizes to account for the footer without scrolling - I'll leave that to you @VKTB ?

2021-01-07 11:00 UTC, VKTB commented
@louise-davies I opened an issue in DataGateway and will provide a fix for it soon. What do we want to do about the below?

>I noticed that the link names change colour after they have been clicked (which is normal behaviour), so I just wanted to get people's view on whether we want to override this? It seems that is overridden in TopCAT and `text-decoration` is set to `none` to remove the lines under the link names. Given that there are some hyperlinks in the _Cookies_ page, it might better to globalise this if we want the same behaviour there.

2021-01-07 14:31 UTC, VKTB commented
The links were difficult to see in dark mode and therefore failed accessibility. I overrode the colours of `<a>` element and they are consistent with the colours used for the links in the cookies page.

Before:
![image](https://user-images.githubusercontent.com/45173816/103903490-da9e1400-50f3-11eb-97dd-f20feac94fc0.png)

After:
![image](https://user-images.githubusercontent.com/45173816/103903506-e093f500-50f3-11eb-90e5-06dc741f8427.png)
![image](https://user-images.githubusercontent.com/45173816/103903514-e4c01280-50f3-11eb-9131-f63b6ed00a1f.png)

2021-01-12 09:17 UTC, louise-davies approved these changes

2021-01-12 10:00 UTC, merged