Persistent login between page refreshes/re-routing #641
ral-facilities/scigateway pull request #670
Opened 2021-03-26 19:47 UTC by sam-glendenning

## Description
Keeps the user logged in after refreshing the web page or navigating to a different address. On page refresh, when auth provider is constructed in code, a check is made for an existing token. If one is found, the user details are parsed from it and stored in code. Otherwise, user is assumed not to be logged in.

No additional data is stored locally, relies on the token being secure and signed. Any changes to the token made by the user invalidate the session and log the user out. This prevents the user from modifying their username or admin status.

Also amending test data in auth provider test code to use a valid JWT as test data instead of the string 'token'. This is to allow for testing to be carried out to confirm user login. The code is unable to parse user details from a token string equalling 'token' so a JWT with test data is used instead.

## Testing instructions
Test with JWT authenticator (username = 'username') and ICAT authenticator (username = 'root'). 

- [ ] Review code
- [ ] Check Actions build
- [ ] After login, validate user who is logged in and their functionality. Then refresh the page or navigate to a different one to check the same functionality exists
- [ ] If logged in as admin user, check navigation to /admin works after page refresh
- [ ] Check token refreshing and validation is happening with requests to /checkToken and /refresh for JWT and /verify for ICAT
- [ ] Review changes to test coverage

## Agile board tracking
closes #641

2021-03-31 13:29 UTC, louise-davies requested changes
Looks good - just a few comments re: typing declarations & removing some commented out code

2021-03-31 13:36 UTC, sam-glendenning commented on src/authentication/baseAuthProvider.tsx
> +        // not a valid JWT, token has likely been tampered with in some way (or we are running tests)
In the console? Or somewhere else?

2021-03-31 13:37 UTC, sam-glendenning commented on cypress/integration/login.spec.ts
> +    );
I'd forgotten I'd added that in. I'll remove the later check, thanks for spotting that.

2021-04-01 14:45 UTC, louise-davies approved these changes
Looks good 👍

2021-04-01 14:50 UTC, merged