nav menu open by default on home #848
ral-facilities/scigateway pull request #857
Opened 2021-12-08 09:46 UTC by joshuadkitenge

## Description
As part of ral-facilities/datagateway#954, the navigation drawer should be open on the datagateway homepage by default.

## Testing instructions
Add a set up instructions describing how the reviewer should test the code

- [ ] Review code
- [ ] Check Actions build
- [ ] Review changes to test coverage
- [ ] {more steps here}

## Agile board tracking
closes #848

2021-12-08 10:07 UTC, joshuadkitenge commented
![default-open](https://user-images.githubusercontent.com/83226114/145189537-21ded1a1-5b2b-4837-9a42-b6cd09ad3e8a.gif)

2021-12-08 15:57 UTC, joelvdavies requested changes
Looks good, just a small change.

2021-12-08 15:57 UTC, joelvdavies commented on cypress/integration/login.spec.ts
> +    cy.get('[aria-label="Close navigation menu"]').should('be.visible');
Could this be change to have 'button' like the others?

2021-12-09 09:08 UTC, joelvdavies approved these changes
CI passes, comment resolved.

2021-12-09 09:09 UTC, merged