Navigation drawer redesign #854
ral-facilities/scigateway pull request #861
Opened 2021-12-09 16:04 UTC by joshuadkitenge

## Description
Navigation Drawer redesign
https://preview.uxpin.com/ee9832eb8102ff6013aad58becab3ea162682ce9#/pages/144657834/simulate/no-panels 

## Testing instructions
Add a set up instructions describing how the reviewer should test the code

- [ ] Review code
- [ ] Check Actions build
- [ ] Review changes to test coverage
- [ ] {more steps here}

## Agile board tracking
closes #854

2021-12-10 16:17 UTC, joshuadkitenge commented
![nav-drawer-2](https://user-images.githubusercontent.com/83226114/145606034-742219c2-b2da-4aa0-979f-14478aa34d2b.gif)

2021-12-10 16:45 UTC, joelvdavies requested changes
Found a few small things. Also I think you should remove `position: 'absolute'` from the STFC logo as currently it ignores all other items in the list when resized e.g. 
![image](https://user-images.githubusercontent.com/90245114/145610096-7eabdf8a-4ae7-4769-a897-4e1a8bc08007.png)
The method Louise used on the homepage is here: https://github.com/ral-facilities/datagateway/pull/985/commits/f3b537fd5c8f3584b74d67a3d00d1a2ea068d859.

2021-12-10 16:45 UTC, joelvdavies commented on src/navigationDrawer/navigationDrawer.component.tsx
> +  // styled,
I think this should be removed.

2021-12-10 16:45 UTC, joelvdavies commented on src/navigationDrawer/navigationDrawer.component.tsx
> +// }));
This also seems unnecessary.

2021-12-10 16:45 UTC, joelvdavies commented on src/navigationDrawer/navigationDrawer.component.tsx
> +
Same for this line.

2021-12-13 14:03 UTC, joelvdavies approved these changes
Looks good and works as expected. Reviewed changes and code coverage, CI passes.

2021-12-13 14:04 UTC, merged